export const data = [
  {
    id: 1,
    userId: "John Doe",
    title: "What is Posts?",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    date: "2022-09-28T21:34:40.616Z",
    comments: ["gggg", "hhhhh"],
  },
  {
    id: 2,
    userId: "Jane Smith",
    title: "What is Posts?",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    date: "2022-09-28T21:34:40.616Z",
    comments: ["gggg", "hhhhh"],
  },
  {
    id: 1,
    userId: "John Doe",
    title: "What is Posts?",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    date: "2022-09-28T21:34:40.616Z",
    comments: ["gggg", "hhhhh"],
  },
  {
    id: 1,
    userId: "John Doe",
    title: "What is Posts?",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    date: "2022-09-28T21:34:40.616Z",
    comments: ["gggg"],
  },
  {
    id: 1,
    userId: "John Doe",
    title: "What is Posts?",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    date: "2022-09-28T21:34:40.616Z",
    comments: ["gggg", "hhhhh", "you are cool"],
  },
  {
    id: 1,
    userId: "John Doe",
    title: "What is Posts?",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    date: "2022-09-28T21:34:40.616Z",
    comments: ["gggg", "hhhhh"],
  },
  {
    id: 1,
    userId: "John Doe",
    title: "What is Posts?",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    date: "2022-09-28T21:34:40.616Z",
    comments: [],
  },
  {
    id: 1,
    userId: "John Doe",
    title: "What is Posts?",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    date: "2022-09-28T21:33:40.616Z",
    comments: ["This is cool", "hhhhh", "greetings"],
  },
  {
    id: 1,
    userId: "John Doe",
    title: "What is Posts?",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    date: "2022-09-28T21:33:40.616Z",
    comments: ["gggg", "hhhhh"],
  },
  {
    id: 1,
    userId: "John Doe",
    title: "What is Posts?",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    date: "2022-09-28T21:33:40.616Z",
    comments: [],
  },
  {
    id: 1,
    userId: "Jane Smith",
    title: "What is Posts?",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    date: "2022-09-28T21:33:40.616Z",
    comments: ["gggg", "hhhhh", "nice!!!", "awesome post"],
  },
  {
    id: 1,
    userId: "Jane Smith",
    title: "What is Posts?",
    body: "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto",
    date: "2022-09-28T21:33:40.616Z",
    comments: ["gggg", "hhhhh", "nice!!!", "awesome post"],
  },
];
