import Head from "next/head";
import { useEffect, useState } from "react";
import PostCard from "../components/postCard";
import { useGetPostsQuery } from "../features/posts/postsSlice";
import Link from "next/link";
import Card from "../components/cards/Card";
import Layout from "../components/layout/Layout";

export default function Home() {
  const [postData, setPostData] = useState(null);
  const {
    isSuccess,
    error,
    isLoading,
    isError,
    data: posts,
  } = useGetPostsQuery();

  useEffect(() => {
    setPostData(posts);
  }, [posts]);

  // console.log("posts", postData);

  return (
    <>
      <Head>
        <title>Frontend task</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* <main className="text-3xl">
        <section>
          {!isLoading &&
            postData?.ids.map((postId) => (
              <PostCard key={postId} post={postData.entities[postId]} />
            ))}
        </section>
      </main> */}

      <Card />
      <footer></footer>
    </>
  );
}
