import Head from "next/head";
import { useEffect, useState } from "react";
// import Link from "next/link";
import PostCard from "../components/postCard";
import { useGetPostsQuery } from "../features/posts/postsSlice";
import Link from "next/link";
import Card from "../components/cards/Card";
import Layout from "../components/layout/Layout";
import { useSelector } from "react-redux";
import {
  addPost,
  removePost,
  selectAllPosts,
  getPostsStatus,
  getPostsError,
} from "../features/posts/postsSlice";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Card />
      </main>
    </>
  );
}
