import Head from "next/head";
import { useSelector } from "react-redux";
import Card from "../components/cards/Card";
import {
  addPost,
  removePost,
  selectAllPosts,
  getPostsStatus,
  getPostsError,
} from "../features/posts/postsSlice";

export default function Home() {
  const posts = useSelector(selectAllPosts);
  const postsStatus = useSelector(getPostsStatus);
  const postsError = useSelector(getPostsError);

  console.log("posts", posts);

  return (
    <>
      <Head>
        <title>Frontend task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Card />
      </main>
    </>
  );
}
